services:
  govdocs-api:
    image: govdocs-api
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDEVMODE=1  # Enables additional debugging information
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # network_mode: host
    volumes:
      - govdocs-api:/app
      - models:/.cache/huggingface
#    runtime: nvidia -> Install nvidia-container toolkit to run models on GPU

volumes:
  govdocs-api:
  models: