services:
  govdocs-api:
    image: govdocs-api
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - HF_HOME=/app/models
    volumes:
      - ./models:/app/models 
    network_mode: host # required to reach supabase on localhost
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # runtime: nvidia -> Install nvidia-container toolkit to run models on GPU
